// Builds every prompt artefact from two sources:
//   briefs/_DESIGN_SPEC.md        the shared design system (single source of truth)
//   briefs/W1-*.md                the per-screen "## SCREEN BRIEF" halves
//
// Emits:
//   briefs/00_DESIGN_INSTRUCTIONS.md   standing instruction — paste ONCE per session
//   briefs/W1-*.md                     full self-contained prompt (spec + screen)
//   briefs/short/W1-*.md               screen only, for after the instruction is loaded
//
// Per-screen content is never modified — only the shared blocks are regenerated.
//
// Run from 04_UI_UX/:  node tools/build-briefs.mjs
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const BRIEFS = 'briefs';
const SHORT = join(BRIEFS, 'short');
const SPEC = join(BRIEFS, '_DESIGN_SPEC.md');
const MARK = '## SCREEN BRIEF';

const COPY_FULL =
  '**Copy everything below the line and paste it into Claude Designer.** Fully self-contained — no repo files needed.\n\n' +
  'Running several screens in one Claude Designer project? Load [`00_DESIGN_INSTRUCTIONS.md`](00_DESIGN_INSTRUCTIONS.md) once instead, then use the short form in [`short/`](short/).';

const COPY_SHORT =
  '**Short form.** Use this ONLY when `00_DESIGN_INSTRUCTIONS.md` is already loaded in the Claude Designer session — pasted at the start, or set as the project\'s custom instructions.\n\n' +
  'If it is not loaded, use the full self-contained version one directory up instead, or the designer will invent its own styling.';

const SHORT_PREAMBLE =
  'Design the following screen.\n\n' +
  '**Apply the design instructions already in this conversation in full** — the non-negotiables, legibility tiers, type scale, palette, spacing, layout shell, frame-safe zones, component states, region formatting and imperfection rules. They are not a starting point to improve on.\n\n' +
  'Canvas 1920 × 1080. Finish with the compliance report.';

// Opens the FULL form only — a per-screen instruction, wrong for the standing doc.
const FULL_PREAMBLE =
  'Design a screen for a film/TV software simulation platform. This is fictional software built to be **filmed**, not used.\n\n' +
  '**Canvas: 1920 × 1080.** Deliver one artboard per state listed at the end, and finish with the compliance report.\n\n---';

// Opens the STANDING INSTRUCTION only — rules now, screens later.
const INSTRUCTION_PREAMBLE =
  'These are the standing design rules for a film/TV software simulation platform — fictional institutional software built to be **filmed**, not used.\n\n' +
  '**Do not design anything yet.** Read and hold these rules. I will send screen briefs one at a time; every one of them follows everything below, and a brief supplies only what is specific to that screen — institution, scene, content, states, imperfections. A brief never overrides these rules.\n\n' +
  'Every screen is 1920 × 1080 and ends with the compliance report in section 11.\n\n' +
  'Reply only that you have read them and are ready for the first screen.\n\n---';

const INSTRUCTION_HEADER = `# Design Instructions — In-World Simulation UI

**This is the governing document for every screen in the catalogue.**

Load it **once** at the start of a Claude Designer session, or set it as the custom instructions of a Claude Designer project. Everything you design in that session follows it. Individual screen briefs supply only what is specific to that screen — institution, scene, content, states, imperfections — and never override what is here.

Generated from \`briefs/_DESIGN_SPEC.md\`. Do not edit this file directly; edit the spec and re-run \`node tools/build-briefs.mjs\`.

---
`;

const spec = readFileSync(SPEC, 'utf8').trim();

// 1. Standing instruction
writeFileSync(
  join(BRIEFS, '00_DESIGN_INSTRUCTIONS.md'),
  `${INSTRUCTION_HEADER}\n${INSTRUCTION_PREAMBLE}\n\n${spec}\n`
);
console.log('wrote briefs/00_DESIGN_INSTRUCTIONS.md');

// 2. Per-screen, both forms
mkdirSync(SHORT, { recursive: true });

const files = readdirSync(BRIEFS)
  .filter((f) => /^W1-\d\d.*\.md$/.test(f))
  .sort();
if (files.length === 0) throw new Error('no W1-*.md briefs found');

for (const f of files) {
  const path = join(BRIEFS, f);
  const src = readFileSync(path, 'utf8');

  const bodyAt = src.indexOf(MARK);
  if (bodyAt < 0) throw new Error(`${f}: no "${MARK}" marker`);
  const body = src.slice(bodyAt).trimEnd();

  const head = src.slice(0, bodyAt);
  const ruleAt = head.search(/^---$/m);
  if (ruleAt < 0) throw new Error(`${f}: no leading --- rule`);

  // Title + any per-screen run notes, minus whichever copy instruction is present.
  const header = head
    .slice(0, ruleAt)
    .split('\n')
    .filter((l) => !/^\*\*Copy everything below the line|^\*\*Short form\.|^Running several screens|^If it is not loaded/.test(l.trim()))
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trimEnd();

  writeFileSync(path, `${header}\n\n${COPY_FULL}\n\n---\n\n${FULL_PREAMBLE}\n\n${spec}\n\n${body}\n`);
  writeFileSync(
    join(SHORT, f),
    `${header}\n\n${COPY_SHORT}\n\n---\n\n${SHORT_PREAMBLE}\n\n${body}\n`
  );
  console.log(`wrote ${f}  +  short/${f}`);
}

console.log(`\n${files.length} screens × 2 forms, plus the standing instruction.`);
